### ISSUE TITLE
git-graph app

### ISSUE THREAD

**Issue by dooraim** [dooraim/ansible-dooraim-role#1]
Add git-graph app, mlange-42/git-graph

```
---
- name: Install git-graph using cargo
  hosts: all
  become: yes
  tasks:
    - name: Ensure Rust and Cargo are installed
      ansible.builtin.package:
        name: rust
        state: present

    - name: Install git-graph using cargo
      ansible.builtin.command: cargo install git-graph
      args:
        chdir: /path/to/your/directory  # Modifica il percorso se necessario

```
